apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-env1 
  labels:
    app: nginx-env1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-env1
  template:
    metadata:
      labels:
        app: nginx-env1 
    spec:
      containers:
        - name: nginx-env1
          imagePullPolicy: Always
          image: path/nginx:0.0.5 
          ports:
            - containerPort: 80
