apiVersion: v1
kind: Service
metadata:
  name: internal-nginx-env1-lb
  labels:
    app: nginx-env1
  annotations:
    "service.beta.kubernetes.io/aws-load-balancer-internal": "10.0.0.0/8" 
spec:
  type: LoadBalancer
  selector:
    app: nginx-env1 
  ports:
    - name: ingress-80 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ingress-443 
      protocol: TCP
      port: 443
      targetPort: 443
#  loadBalancerSourceRanges:
#    - "10.0.0.0/8" # ingress example 
#    - "192.168.1.0/8" # ingress example
#    - "0.0.0.0/0" # ingress example, experiment
