apiVersion: v1
kind: Service
metadata:
  name: nginx-env1-lb
  labels:
    app: nginx-env1 
spec:
  type: LoadBalancer
  selector:
    app: nginx-env1 
  ports:
    - name: ingress-80 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ingress-443 
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerSourceRanges:
    # - "0.0.0.0/0"
    - "<public IP>/32" # Paul Stivers
