apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-env2 
  labels:
    app: nginx-env2 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-env2
  template:
    metadata:
      labels:
        app: nginx-env2
    spec:
      containers:
        - name: nginx-env2
          imagePullPolicy: Always
          image: path/nginx:0.0.4
          ports:
            - containerPort: 80
