apiVersion: v1
kind: Service
metadata:
  name: nginx-env2-lb
  labels:
    app: nginx-env2 
spec:
  type: LoadBalancer
  selector:
    app: nginx-env2 
  ports:
    - name: ingress-80 
      protocol: TCP
      port: 80
      targetPort: 80
    - name: ingress-443 
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerSourceRanges:
    # - "10.0.0.0/8"
    # - "192.168.1.0/8"
    # - "0.0.0.0/0"
    - "<public IP>/32"
